package com.example.TeamApp.excludedUI

suspend fun getPlaceSuggestions(query: String): List<String> {
    // Tu można zaimplementować logikę pobierania danych z Google Places API
    // Na razie zwracamy fikcyjne dane
    return if (query.isNotEmpty()) {
        listOf(
            "Kraków, ul. Floriańska",
            "Kraków, ul. Grodzka",
            "Kraków, ul. Długa",
            "Kraków, ul. Starowiślna",
            "Kraków, ul. Kazimierza Wielkiego",
            "Kraków, ul. Wawelska",
            "Kraków, ul. Karmelicka",
            "Kraków, ul. Dietla",
            "Kraków, ul. Mikołajska",
            "Kraków, ul. Miodowa",
            "Kraków, ul. Świętego Tomasza",
            "Kraków, ul. Rynek Główny",
            "Kraków, ul. Józefa",
            "Kraków, ul. Wita Stwosza",
            "Kraków, ul. Czysta",
            "Kraków, ul. Prądnik Biały",
            "Kraków, ul. Nowa",
            "Kraków, ul. Kościuszki",
            "Kraków, ul. Świętego Jana",
            "Kraków, ul. Mściwoja",
            "Kraków, ul. Główna",
            "Kraków, ul. Biskupa Jordana",
            "Kraków, ul. Pasterska",
            "Kraków, ul. Słowackiego",
            "Kraków, ul. Sienna",
            "Kraków, ul. Łobzowska",
            "Kraków, ul. Rzeźnicza",
            "Kraków, ul. Wilhelma",
            "Kraków, ul. Polan",
            "Kraków, ul. Anczyca",
            "Kraków, ul. Bożego Ciała",
            "Kraków, ul. Dąbska",
            "Kraków, ul. Malwowa",
            "Kraków, ul. Górczyńska",
            "Kraków, ul. Twardowskiego",
            "Kraków, ul. Dąbrowskiego",
            "Kraków, ul. Księcia Józefa",
            "Kraków, ul. Nowohucka",
            "Kraków, ul. Skarżyńskiego",
            "Kraków, ul. Kaczorówka",
            "Kraków, ul. Stradomska",
            "Kraków, ul. Myślenicka",
            "Kraków, ul. Wrocławska",
            "Kraków, ul. Złota",
            "Kraków, ul. Targowa",
            "Kraków, ul. Mściwoja",
            "Kraków, ul. Odrowążów",
            "Kraków, ul. Wincentego",
            "Kraków, ul. Skarbka",
            "Kraków, ul. Żywiecka",
            "Kraków, ul. Krakowska",
            "Kraków, ul. Kalwaryjska",
            "Kraków, ul. Krowoderska",
            "Kraków, ul. Dąbrowskiego",
            "Kraków, ul. Lwowska",
            "Kraków, ul. Płaszowska",
            "Kraków, ul. Międzynarodowa",
            "Kraków, ul. Jawornik",
            "Kraków, ul. Obrońców",
            "Kraków, ul. Olszańska",
            "Kraków, ul. Węgierska",
            "Kraków, ul. Gliniana",
            "Kraków, ul. Polan",
            "Kraków, ul. Wolności",
            "Kraków, ul. Strzeszyńska",
            "Kraków, ul. Ziemowita",
            "Kraków, ul. Kłodzka",
            "Kraków, ul. Kolejowa",
            "Kraków, ul. Skarżyńskiego",
            "Kraków, ul. Sołtysowska",
            "Kraków, ul. Reja",
            "Kraków, ul. Wróblowicka",
            "Kraków, ul. Berberysowa",
            "Kraków, ul. Tuchowska",
            "Kraków, ul. Lecha",
            "Kraków, ul. Cegielniana",
            "Kraków, ul. Rozdzienskiego",
            "Kraków, ul. Bławatna",
            "Kraków, ul. Koralowa",
            "Kraków, ul. Nowotarska",
            "Kraków, ul. Brzoskwiniowa",
            "Kraków, ul. Poniatowskiego",
            "Kraków, ul. Wiejska",
            "Kraków, ul. Wąska",
            "Kraków, ul. Mała",
            "Kraków, ul. Rynkowska",
            "Kraków, ul. Głogowska",
            "Kraków, ul. Żurawinowa",
            "Kraków, ul. Wieczorna",
            "Kraków, ul. Południowa",
            "Kraków, ul. Spółdzielcza",
            "Kraków, ul. Pięciomorgowa",
            "Kraków, ul. Reprezentacyjna",
            "Kraków, ul. Młynarska",
            "Kraków, ul. Strzeszyńska",
            "Kraków, ul. Olszówka",
            "Kraków, ul. Przewóz",
            "Kraków, ul. Chorzowska",
            "Kraków, ul. Kryształowa",
            "Kraków, ul. Wylotowa",
            "Kraków, ul. Świerkowa",
            "Kraków, ul. Szkolna",
            "Kraków, ul. Naramowicka"
        ).filter { it.contains(query, ignoreCase = true) }.take(5)
    } else {
        emptyList()
    }
}